# Generated by Django 3.0.3 on 2020-02-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200215_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='summary',
            field=models.TextField(default='Test', verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
