# Generated by Django 3.0.3 on 2020-02-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1.5, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
