# Generated by Django 3.0.3 on 2020-02-23 03:13

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('summary', ckeditor.fields.RichTextField(verbose_name='Resumo')),
                ('image', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Conteúdo')),
                ('public', models.BooleanField(default=False, verbose_name='Postagem pública')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Postado em')),
                ('tags', models.ManyToManyField(related_name='tags', to='blog.Tag')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-created_at'],
            },
        ),
    ]
