# Generated by Django 3.0.3 on 2020-02-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Inscrito', 'verbose_name_plural': 'Inscritos'},
        ),
    ]
